name: PlayerMention
version: 1.0
main: com.galaxycraft.playermention.PlayerMention
author: iLeean
description: A Plugin that plays a sound when a player is mentioned in the chat.
api-version: 1.17
commands:
    pm:
      description: Main command of the plugin.
      aliases:
        - playermention
        - pm
      permission: pm.use
    reload:
      description: Reloads the plugin configuration.
      usage: /pm reload
      permission: pm.reload